### ISSUE TITLE
How to log sessions into sublist under task

### ISSUE THREAD

**Issue by watts-the-point** [eatgrass/obsidian-pomodoro-timer#21]
In the documentation, there's a section that shows pomodoro logs as subtasks under a task like this

- [ ] Task
   - 🍅 (pomodoro::WORK) (duration:: 25m) (begin:: 2024-01-10 11:45) - (end:: 2024-01-10 12:10) 

Because of this, I can't get the dataviewjs table tracking how many sessions each task took to run. 

I appreciate any help you can offer. #

**Comment by eatgrass** [comment]
Hi, @watts-the-point 
Currently, you need to manually move the logs under each task item. However, I'm already working on an update that will automate this process. In a future release, you'll be able to automatically append logs right after task items, which should make tracking and visualizing a lot easier.

**Comment by watts-the-point** [comment]
Oh okay. I was worried I was missing something obvious. Looking forward to the update!

**Comment by eatgrass** [comment]
Hey @watts-the-point, because of some technical reasons, I've decided not to implement the feature of adding logs directly under tasks, however, you can still use the recently updated
task-tracking feature, which I personally think is a better choice since it's easier and more straightforward for task tracking.

If you need any more assistance with this or anything else, feel free to ask!
