### ISSUE TITLE
Feature Request: use with day planner

### ISSUE THREAD

**Issue by kin30528** [eatgrass/obsidian-pomodoro-timer#41]
Hi @eatgrass, thank you for make the great plugin! I think this plugin is perfect for use with [day planner](https://github.com/ivan-lednev/obsidian-day-planner).

Here's a sample of what it looks like
- [ ] 12:30 - 12:55 task Information ⏳ 2024-03-04

If the pomodoro timer can automatically fill in the time (12:30 - 12:55) and date (⏳ 2024-03-04), it can appear in the “time line” and “week planner” of day planner plugin.

![圖片](https://github.com/eatgrass/obsidian-pomodoro-timer/assets/121107652/55810f52-6402-4dbc-890b-368bf6318b0a)

![圖片](https://github.com/eatgrass/obsidian-pomodoro-timer/assets/121107652/7a7a11cb-7972-432f-a3a0-03e08189ce66)

This is a nice project. However, there are some problems. For example, how to change the time when a task has a second tomato, but if  pomodoro-timer  can only add the time of one tomato in each checkbox, I think it's also very useful!

The conditions for the time line and week planner of day planner plugin to be successfully display a task are as follows:
1. only for check box
2. make a custom tag in checkbox or properties
3. write a time (12:30 - 12:55) and date (⏳ 2024-03-04) in check box.

I think it would be a good idea to just display checkboxes with custom tag in pomodoro-time. This would help pomodoro-time to show checkboxes that as the mission require tomato time to completeand, instead of checkboxes that as  the Reminder.

Finally, thank you again for your work with ob users!

**Comment by dinchamion** [comment]
I implemented this functionality, albeit with a workaround, so if there's a native way to do this, it'd be more convenient. But here's what I did:

- enabled _Task Tracking_
- installed **Templater**
- set the _log format_ to **Custom**:
```
<%*
if (log.mode == "WORK") {
  if (!log.finished) {
    tR = `- 🟢 ${log.task.name} ${log.begin.format("HH:mm")} - ${log.end.format(
    "HH:mm"
  )}`;
  } else {
    tR = `- 🟢 ${log.task.name} ${log.begin.format("HH:mm")} - ${log.end.format(
    "HH:mm"
  )}`;
  }
} else {
  tR = `- ☕️ Break ${log.begin.format("HH:mm")}-${log.end.format(
    "HH:mm"
  )}`;
}
%>
```
- enabled _Prefer saving to task file_
- added a section at the bottom of my daily note template called "Activities"

This way all sessions are added to the bottom of my daily note. I use the task tracking feature, so it's auto-populating the task text and marks the pomodoro sessions on the task itself. And the pomodoro sessions are added to Day Planner's timeline.

I disabled breaks, because I seldom use them, that's why my custom log format is the way it is. (And also because I don't know how to remove the IF logic, so this way I don't have to care. Might revisit it at some point.)

Of course, your needs may be different, but this works for me.

<img width="698" alt="Screenshot 2024-10-23 at 11 04 50" src="https://github.com/user-attachments/assets/5102ee33-c148-41f6-b126-63f9f09ea1d3">
<img width="293" alt="Screenshot 2024-10-23 at 11 05 01" src="https://github.com/user-attachments/assets/856b9442-2a09-47f9-8884-72d1d507a995">

**Comment by kin30528** [comment]
@dinchamion Wow, its amazing.

I previously learned to use the software Autohotkey, which allows me to calculate and automatically generate the Day Planner format using hotkeys, while keeping my daily note in the original pomodoro-timer format.
<img width="198" alt="1" src="https://github.com/user-attachments/assets/93f4d4b1-78ef-4386-8548-48eb665946a2">
<img width="201" alt="2" src="https://github.com/user-attachments/assets/c916d6a3-5dc3-4ded-bafa-bc8d63dba53e">

Finally, I use Dataview to calculate the time spent on specific task (such as “♜ 1-1”) and the total time (“WORK”, such as 1-1~2-5) spent on all tasks.
<img width="509" alt="3" src="https://github.com/user-attachments/assets/7cb17258-3875-419a-81d5-978105e8d6a1">

It helps me to use the pomodoro-timer to track and log time, while DayPlanner can display task information and the time spent on each task.

Anyway, your method is more efficient~~ Thank you.
